spring:
  application:
    name: wallet-service

  datasource:
    url: jdbc:postgresql://localhost:5432/payment
    username: payment
    password: payment
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  cloud:
    function:
      definition: transactionCreated
    stream:
      bindings:
        transactionCreated-in-0:
          destination: payments.transaction.v1
          group: wallet-service
          content-type: application/json
      kafka:
        binder:
          brokers: localhost:9092

  server:
    port: 8082