spring:
  application:
    name: fraud-service

  datasource:
    url: jdbc:postgresql://localhost:5432/payment
    username: payment
    password: payment
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  cloud:
    function:
      definition: walletReserved
    stream:
      bindings:
        walletReserved-in-0:
          destination: payments.wallet.v1
          group: fraud-service
          content-type: application/json
      kafka:
        binder:
          brokers: localhost:9092

server:
  port: 8083